"""Regenerate checked-in properties after a C-header change (install fosu first)."""
from pathlib import Path
import fosu
from fosu._native import ffi

start = '''# Generated by python/generate_stubs.py; checked against the compiled API in tests.
from collections.abc import Iterator, Sequence
from enum import IntFlag
from os import PathLike
from typing import Any, TypeVar, overload
import sys
if sys.version_info >= (3, 12):
    from collections.abc import Buffer
else:
    from typing_extensions import Buffer

_T = TypeVar("_T", covariant=True)
NO_SLIDER: int

class Sections(IntFlag):
    GENERAL = 2
    EDITOR = 4
    METADATA = 8
    DIFFICULTY = 16
    EVENTS = 32
    TIMING_POINTS = 64
    COLOURS = 128
    HIT_OBJECTS = 256
    ALL = 510

class RecordSequence(Sequence[_T]):
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> _T: ...
    @overload
    def __getitem__(self, index: slice) -> RecordSequence[_T]: ...
    def __iter__(self) -> Iterator[_T]: ...
    def to_numpy(self) -> Any: ...
    def __array__(self, dtype: Any = None, copy: bool | None = None) -> Any: ...

'''
extra = {
    'Beatmap': dict(source_size='int', text='memoryview', stats='ParseStats', hit_objects='RecordSequence[HitObject]',
                    sliders='RecordSequence[Slider]', slider_points='RecordSequence[Point]',
                    timing_points='RecordSequence[TimingPoint]', breaks='RecordSequence[Break]',
                    combo_colours='RecordSequence[int]'),
    'HitObject': dict(slider_index='int', slider='Slider | None', is_circle='bool',
                     is_slider='bool', is_spinner='bool', is_hold='bool', is_new_combo='bool'),
    'Slider': dict(points='RecordSequence[Point]'),
}
bools = {'letterbox_in_breaks', 'widescreen_storyboard', 'epilepsy_warning', 'special_style',
         'use_skin_sprites', 'samples_match_playback_rate', 'uninherited'}
for name, ctype in [('Beatmap', 'fosu_metadata'), ('HitObject', 'fosu_hit_object'),
                    ('Slider', 'fosu_slider'), ('Point', 'fosu_point'),
                    ('TimingPoint', 'fosu_timing_point'), ('Break', 'fosu_break'), ('ParseStats', 'fosu_stats')]:
    start += f'class {name}:\n'
    for field, definition in ffi.typeof(ctype).fields:
        if field == 'reserved' or (name == 'HitObject' and field == 'slider'):
            continue
        ty = definition.type
        annotation = ('bool' if field in bools else 'str' if ty == ffi.typeof('fosu_string_ref')
                      or ty.cname == 'char' else 'float' if ty.cname == 'double' else 'int')
        start += f'    @property\n    def {field}(self) -> {annotation}: ...\n'
    for field, annotation in extra.get(name, {}).items():
        start += f'    @property\n    def {field}(self) -> {annotation}: ...\n'
    start += '\n'
start += '''def parse(data: Buffer, *, sections: Sections | int = Sections.ALL) -> Beatmap: ...
def parse_file(path: str | bytes | PathLike[str] | PathLike[bytes], *, sections: Sections | int = Sections.ALL) -> Beatmap: ...
'''
Path(__file__).with_name('fosu').joinpath('__init__.pyi').write_text(start)
