find_package(Python REQUIRED COMPONENTS Interpreter)
find_package(Threads REQUIRED)
# Test both real engine builds, rather than a scalar-shaped route compiled
# with SIMD helpers. Keep their inline symbols isolated from each other.
add_library(test_scalar_engine SHARED EXCLUDE_FROM_ALL tests/reference/scalar_engine.cc)
fosu_configure(test_scalar_engine scalar native)
set_target_properties(test_scalar_engine PROPERTIES
  CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
if(BUILD_TESTING)
  set(_tests numeric sections string_lookup hitobject_fields storage hardening c_api c_api_unload)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT FOSU_SANITIZE)
    list(APPEND _tests c_api_io)
  endif()
  set(_test_targets)
  foreach(name IN LISTS _tests)
    list(APPEND _test_targets test_${name})
    fosu_executable(test_${name} tests/test_${name}.cc)
    target_compile_options(test_${name} PRIVATE -UNDEBUG)
    target_link_libraries(test_${name} PRIVATE test_scalar_engine)
    if(name MATCHES "^(c_api|c_api_io)$")
      target_link_libraries(test_${name} PRIVATE fosu Threads::Threads)
    endif()
    if(name STREQUAL "c_api_unload")
      target_link_libraries(test_${name} PRIVATE ${CMAKE_DL_LIBS})
      add_test(NAME ${name} COMMAND test_${name} $<TARGET_FILE:fosu>)
    elseif(name STREQUAL "c_api_io")
      if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT FOSU_SANITIZE)
        add_test(NAME ${name} COMMAND test_${name})
      endif()
    else()
      add_test(NAME ${name} COMMAND test_${name})
    endif()
  endforeach()
  set_tests_properties(numeric sections string_lookup hitobject_fields storage hardening PROPERTIES LABELS parser)
  set_tests_properties(c_api c_api_unload PROPERTIES LABELS c-api)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT FOSU_SANITIZE)
    set(_export_args)
    if(FOSU_BUNDLE_RUNTIME)
      list(APPEND _export_args --bundled)
    endif()
    add_test(NAME library_exports COMMAND Python::Interpreter ${PROJECT_SOURCE_DIR}/tests/test_library_exports.py $<TARGET_FILE:fosu> ${_export_args})
    # Inspect ELF on the host; do not run host Python through a target emulator.
    add_test(NAME binary_hardening COMMAND "${Python_EXECUTABLE}" ${PROJECT_SOURCE_DIR}/tests/test_binary_hardening.py $<TARGET_FILE:fosu>)
    set_tests_properties(library_exports binary_hardening c_api_io PROPERTIES LABELS c-api)
    foreach(kind avx2 neon)
      if(TARGET fosu_native_${kind})
        add_test(NAME engine_exports COMMAND Python::Interpreter ${PROJECT_SOURCE_DIR}/tests/test_library_exports.py $<TARGET_FILE:fosu_native_${kind}> --engine ${_export_args})
        add_test(NAME engine_hardening COMMAND "${Python_EXECUTABLE}" ${PROJECT_SOURCE_DIR}/tests/test_binary_hardening.py $<TARGET_FILE:fosu_native_${kind}>)
        set_tests_properties(engine_exports engine_hardening PROPERTIES LABELS c-api)
      endif()
    endforeach()
  endif()
  add_executable(test_dispatch EXCLUDE_FROM_ALL tests/test_dispatch.cc)
  fosu_configure(test_dispatch scalar native)
  target_compile_options(test_dispatch PRIVATE -UNDEBUG)
  target_link_libraries(test_dispatch PRIVATE fosu Threads::Threads)
  foreach(backend auto scalar avx2 neon invalid)
    add_test(NAME dispatch_${backend} COMMAND test_dispatch ${backend})
    set_tests_properties(dispatch_${backend} PROPERTIES LABELS c-api)
  endforeach()
  add_custom_target(test-binaries DEPENDS ${_test_targets} test_dispatch)
  add_custom_target(check COMMAND ${CMAKE_CTEST_COMMAND} --output-on-failure -LE oneshot DEPENDS test-binaries USES_TERMINAL)
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    fosu_executable(fuzz_parser tests/fuzz_parser.cc)
    target_link_libraries(fuzz_parser PRIVATE test_scalar_engine)
    target_compile_options(fuzz_parser PRIVATE -O1 -g -UNDEBUG -fsanitize=fuzzer,address,undefined,float-cast-overflow -fno-sanitize-recover=all)
    target_link_options(fuzz_parser PRIVATE -fsanitize=fuzzer,address,undefined,float-cast-overflow)
    set(FOSU_FUZZ_SECONDS 60 CACHE STRING "Fuzz smoke duration")
    add_custom_target(fuzz-smoke
      COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/fuzz-corpus
      COMMAND ${CMAKE_COMMAND} -E copy_directory ${PROJECT_SOURCE_DIR}/tests/fuzz-seeds ${CMAKE_CURRENT_BINARY_DIR}/fuzz-corpus
      COMMAND fuzz_parser ${CMAKE_CURRENT_BINARY_DIR}/fuzz-corpus -dict=${PROJECT_SOURCE_DIR}/tests/parser.dict -max_total_time=${FOSU_FUZZ_SECONDS} -max_len=65536 -artifact_prefix=${CMAKE_CURRENT_BINARY_DIR}/
      DEPENDS fuzz_parser USES_TERMINAL)
  endif()
endif()

foreach(name native c_api)
  fosu_executable(reference_${name} tests/reference/${name}.cc)
  target_compile_options(reference_${name} PRIVATE -UNDEBUG)
endforeach()
target_link_libraries(reference_c_api PRIVATE fosu)
add_library(numeric_oracle SHARED EXCLUDE_FROM_ALL tests/reference/numeric.cc)
target_link_libraries(numeric_oracle PRIVATE fosu_headers)
target_compile_definitions(numeric_oracle PRIVATE FOSU_DISABLE_SIMD)
fosu_profile(numeric_oracle)
target_compile_options(numeric_oracle PRIVATE -UNDEBUG)
set_target_properties(numeric_oracle PROPERTIES PREFIX "" CXX_VISIBILITY_PRESET hidden)
# The oracle intentionally has no ISA tuning and remains independent of the fast path.
fosu_executable(validate_corpus tests/validate_corpus.cc)
target_compile_options(validate_corpus PRIVATE -UNDEBUG)
target_link_libraries(validate_corpus PRIVATE ${CMAKE_DL_LIBS} test_scalar_engine)
add_custom_target(references DEPENDS reference_native reference_c_api numeric_oracle validate_corpus)

foreach(name native c_api)
  add_library(library_${name} SHARED EXCLUDE_FROM_ALL bench/library_module.cc)
  if(name STREQUAL "c_api")
    fosu_dispatch(library_${name} native)
  else()
    fosu_configure(library_${name} "${_header_isa}" native)
  endif()
  set_target_properties(library_${name} PROPERTIES PREFIX "" CXX_VISIBILITY_PRESET hidden)
endforeach()
target_sources(library_c_api PRIVATE src/fosu/bindings/c_api.cc)
target_compile_definitions(library_c_api PRIVATE FOSU_BENCH_CAPI)
fosu_runtime(library_c_api)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  target_link_options(library_c_api PRIVATE -Wl,-Bsymbolic)
endif()
foreach(name library_compare library_first profile_parse prefix generate_corpus)
  fosu_executable(${name} bench/${name}.cc)
endforeach()
target_link_libraries(library_compare PRIVATE ${CMAKE_DL_LIBS})
target_compile_options(profile_parse PRIVATE -g)
fosu_executable(c_api_first bench/c_api_first.c)
set_property(TARGET c_api_first PROPERTY C_STANDARD 11)
target_compile_definitions(c_api_first PRIVATE _POSIX_C_SOURCE=200809L "FOSU_DEFAULT_LIBRARY=\"$<TARGET_FILE:fosu>\"")
target_link_libraries(c_api_first PRIVATE ${CMAKE_DL_LIBS})
add_dependencies(c_api_first fosu)
add_custom_target(bench-build DEPENDS library_native library_c_api library_compare library_first c_api_first profile_parse prefix generate_corpus)

if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND _x86)
  add_executable(oneshot_process EXCLUDE_FROM_ALL bench/oneshot_process.c)
  target_compile_options(oneshot_process PRIVATE -Wall -Wextra)
  set(FOSU_ONESHOT_CXX g++ CACHE FILEPATH "GCC compiler for the freestanding one-shot")
  set(FOSU_ONESHOT_FLAGS "" CACHE STRING "Additional one-shot compiler flags")
  separate_arguments(_oneshot_flags NATIVE_COMMAND "${FOSU_ONESHOT_FLAGS}")
  get_target_property(_oneshot_headers fosu_headers HEADER_SET)
  add_custom_command(OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/fosu_oneshot
    COMMAND ${CMAKE_COMMAND} -E env CXX=${FOSU_ONESHOT_CXX} sh oneshot/build.sh ${CMAKE_CURRENT_BINARY_DIR}/fosu_oneshot ${_oneshot_flags}
    DEPENDS oneshot/main.cc oneshot/runtime.h oneshot/build.sh tests/support/canonical_dump.h ${_oneshot_headers}
    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR} VERBATIM)
  add_custom_target(oneshot DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/fosu_oneshot)
  if(BUILD_TESTING)
    add_test(NAME oneshot_output COMMAND Python::Interpreter ${PROJECT_SOURCE_DIR}/tests/test_oneshot.py $<TARGET_FILE:reference_native> ${CMAKE_CURRENT_BINARY_DIR}/fosu_oneshot)
    add_test(NAME oneshot_limits COMMAND Python::Interpreter ${PROJECT_SOURCE_DIR}/tests/test_oneshot_limits.py ${CMAKE_CURRENT_BINARY_DIR}/fosu_oneshot)
    set_tests_properties(oneshot_output oneshot_limits PROPERTIES LABELS oneshot)
    add_custom_target(check-oneshot COMMAND ${CMAKE_CTEST_COMMAND} --output-on-failure -L oneshot DEPENDS oneshot reference_native USES_TERMINAL)
  endif()
endif()
