find_package(Python REQUIRED COMPONENTS Interpreter)
find_package(Threads REQUIRED)
# Test both real engine builds, rather than a scalar-shaped route compiled
# with SIMD helpers. Keep their inline symbols isolated from each other.
add_library(test_scalar_engine SHARED EXCLUDE_FROM_ALL tests/reference/scalar_engine.cc)
fosu_configure(test_scalar_engine scalar native)
set_target_properties(test_scalar_engine PROPERTIES
  CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
if(BUILD_TESTING)
  set(_tests numeric sections string_lookup hitobject_fields storage hardening)
  set(_test_targets)
  foreach(name IN LISTS _tests)
    list(APPEND _test_targets test_${name})
    fosu_executable(test_${name} tests/test_${name}.cc)
    target_compile_options(test_${name} PRIVATE -UNDEBUG)
    target_link_libraries(test_${name} PRIVATE test_scalar_engine)
    add_test(NAME ${name} COMMAND test_${name})
  endforeach()
  set_tests_properties(numeric sections string_lookup hitobject_fields storage hardening PROPERTIES LABELS parser)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT FOSU_SANITIZE)
    set(_export_args)
    if(FOSU_BUNDLE_RUNTIME)
      list(APPEND _export_args --bundled)
    endif()
    add_test(NAME library_exports COMMAND Python::Interpreter ${PROJECT_SOURCE_DIR}/tests/test_library_exports.py $<TARGET_FILE:fosu> ${_export_args})
    # Inspect ELF on the host; do not run host Python through a target emulator.
    add_test(NAME binary_hardening COMMAND "${Python_EXECUTABLE}" ${PROJECT_SOURCE_DIR}/tests/test_binary_hardening.py $<TARGET_FILE:fosu>)
    foreach(kind avx2 neon)
      if(TARGET fosu_native_${kind})
        add_test(NAME engine_exports COMMAND Python::Interpreter ${PROJECT_SOURCE_DIR}/tests/test_library_exports.py $<TARGET_FILE:fosu_native_${kind}> --engine ${_export_args})
        add_test(NAME engine_hardening COMMAND "${Python_EXECUTABLE}" ${PROJECT_SOURCE_DIR}/tests/test_binary_hardening.py $<TARGET_FILE:fosu_native_${kind}>)
      endif()
    endforeach()
  endif()
  add_executable(test_dispatch EXCLUDE_FROM_ALL tests/test_dispatch.cc)
  fosu_configure(test_dispatch scalar native)
  target_compile_options(test_dispatch PRIVATE -UNDEBUG)
  target_link_libraries(test_dispatch PRIVATE fosu Threads::Threads)
  foreach(kind avx2 neon)
    if(TARGET fosu_native_${kind})
      target_compile_definitions(test_dispatch PRIVATE FOSU_TEST_${kind})
    endif()
  endforeach()
  foreach(backend auto scalar avx2 neon invalid)
    add_test(NAME dispatch_${backend} COMMAND test_dispatch ${backend})
  endforeach()
  add_custom_target(test-binaries DEPENDS ${_test_targets} test_dispatch)
  add_custom_target(check COMMAND ${CMAKE_CTEST_COMMAND} --output-on-failure DEPENDS test-binaries USES_TERMINAL)
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    fosu_executable(fuzz_parser tests/fuzz_parser.cc)
    target_link_libraries(fuzz_parser PRIVATE test_scalar_engine)
    target_compile_options(fuzz_parser PRIVATE -O1 -g -UNDEBUG -fsanitize=fuzzer,address,undefined,float-cast-overflow -fno-sanitize-recover=all)
    target_link_options(fuzz_parser PRIVATE -fsanitize=fuzzer,address,undefined,float-cast-overflow)
    set(FOSU_FUZZ_SECONDS 60 CACHE STRING "Fuzz smoke duration")
    add_custom_target(fuzz-smoke
      COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/fuzz-corpus
      COMMAND ${CMAKE_COMMAND} -E copy_directory ${PROJECT_SOURCE_DIR}/tests/fuzz-seeds ${CMAKE_CURRENT_BINARY_DIR}/fuzz-corpus
      COMMAND fuzz_parser ${CMAKE_CURRENT_BINARY_DIR}/fuzz-corpus -dict=${PROJECT_SOURCE_DIR}/tests/parser.dict -max_total_time=${FOSU_FUZZ_SECONDS} -max_len=65536 -artifact_prefix=${CMAKE_CURRENT_BINARY_DIR}/
      DEPENDS fuzz_parser USES_TERMINAL)
  endif()
endif()

fosu_executable(reference_native tests/reference/native.cc)
target_compile_options(reference_native PRIVATE -UNDEBUG)
add_library(numeric_oracle SHARED EXCLUDE_FROM_ALL tests/reference/numeric.cc)
target_link_libraries(numeric_oracle PRIVATE fosu_headers)
target_compile_definitions(numeric_oracle PRIVATE FOSU_DISABLE_SIMD)
fosu_profile(numeric_oracle)
target_compile_options(numeric_oracle PRIVATE -UNDEBUG)
set_target_properties(numeric_oracle PROPERTIES PREFIX "" CXX_VISIBILITY_PRESET hidden)
# The oracle intentionally has no ISA tuning and remains independent of the fast path.
fosu_executable(validate_corpus tests/validate_corpus.cc)
target_compile_options(validate_corpus PRIVATE -UNDEBUG)
target_link_libraries(validate_corpus PRIVATE ${CMAKE_DL_LIBS} test_scalar_engine)
add_custom_target(references DEPENDS reference_native numeric_oracle validate_corpus)

add_library(library_native SHARED EXCLUDE_FROM_ALL bench/library_module.cc)
fosu_configure(library_native "${_header_isa}" native)
set_target_properties(library_native PROPERTIES PREFIX "" CXX_VISIBILITY_PRESET hidden)
foreach(name library_compare profile_parse generate_corpus)
  fosu_executable(${name} bench/${name}.cc)
endforeach()
target_link_libraries(library_compare PRIVATE ${CMAKE_DL_LIBS})
target_compile_options(profile_parse PRIVATE -g)
add_custom_target(bench-build DEPENDS library_native library_compare profile_parse generate_corpus)
