if(WIN32)
  find_package(Python REQUIRED COMPONENTS Interpreter Development.Module)
  list(GET Python_LIBRARIES 0 _python_library)
  get_filename_component(_python_library_directory "${_python_library}" DIRECTORY)
  set(_python_sabi_library "${_python_library_directory}/python3.lib")
  if(NOT EXISTS "${_python_sabi_library}")
    message(FATAL_ERROR "python3.lib was not found beside the Windows Python installation")
  endif()
  add_library(Python::SABIModule INTERFACE IMPORTED)
  set_target_properties(Python::SABIModule PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${Python_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${_python_sabi_library}")
else()
  find_package(Python REQUIRED COMPONENTS Interpreter Development.SABIModule)
endif()

Python_add_library(_core MODULE USE_SABI 3.10 WITH_SOABI src/fosu/bindings/python.cc)
fosu_dispatch(_core python)
fosu_runtime(_core)
set_target_properties(_core PROPERTIES CXX_VISIBILITY_PRESET hidden
  LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/python-engine")
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  target_link_options(_core PRIVATE "-Wl,--version-script=${PROJECT_SOURCE_DIR}/python/core.map")
  set_property(TARGET _core APPEND PROPERTY LINK_DEPENDS "${PROJECT_SOURCE_DIR}/python/core.map")
elseif(APPLE)
  target_link_options(_core PRIVATE "-Wl,-exported_symbol,_PyInit__core")
endif()
install(TARGETS _core LIBRARY DESTINATION fosu RUNTIME DESTINATION fosu)
