find_package(Python REQUIRED COMPONENTS Interpreter Development.SABIModule)
set(_variants scalar)
if(_x86)
  list(APPEND _variants avx2)
endif()
foreach(variant IN LISTS _variants)
  set(generated "${CMAKE_CURRENT_BINARY_DIR}/_native_${variant}.cpp")
  add_custom_command(OUTPUT "${generated}"
    COMMAND Python::Interpreter "${PROJECT_SOURCE_DIR}/python/build_ffi.py" "${variant}" "${generated}"
    DEPENDS python/build_ffi.py include/fosu/c_api.h VERBATIM)
  Python_add_library(_native_${variant} MODULE USE_SABI 3.10 WITH_SOABI "${generated}" src/c_api.cpp)
  fosu_configure(_native_${variant} "${variant}" python)
  fosu_runtime(_native_${variant})
  set_target_properties(_native_${variant} PROPERTIES CXX_VISIBILITY_PRESET hidden)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    target_link_options(_native_${variant} PRIVATE "-Wl,--version-script=${PROJECT_SOURCE_DIR}/python/${variant}.map")
    set_property(TARGET _native_${variant} APPEND PROPERTY LINK_DEPENDS "${PROJECT_SOURCE_DIR}/python/${variant}.map")
  elseif(APPLE)
    target_link_options(_native_${variant} PRIVATE "-Wl,-exported_symbol,_PyInit__native_${variant}")
  endif()
  install(TARGETS _native_${variant} LIBRARY DESTINATION fosu)
endforeach()
